# Generated by Django 4.2.7 on 2023-12-01 19:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('place', models.CharField(max_length=50, verbose_name='Location of the land')),
                ('ammount', models.IntegerField(verbose_name='Number of trees')),
                ('img', models.ImageField(upload_to='Land', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Latitude')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Length')),
            ],
            options={
                'verbose_name': 'Land',
                'verbose_name_plural': 'Lands',
            },
        ),
        migrations.CreateModel(
            name='TypeTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('typetree', models.CharField(max_length=50, verbose_name='Type of tree')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land', to='land.land')),
            ],
            options={
                'verbose_name': 'Type Tree',
                'verbose_name_plural': 'Type Trees',
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('typetree', models.CharField(max_length=50, verbose_name='type of trees')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='land.land')),
            ],
            options={
                'verbose_name': 'Tree',
                'verbose_name_plural': 'Trees',
            },
        ),
    ]
