# Generated by Django 4.2.7 on 2023-12-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Land', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='land',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=5, verbose_name='Latitude'),
        ),
    ]
