# Generated by Django 4.2.7 on 2023-12-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_alter_land_img_alter_land_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='land',
            name='length',
            field=models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Length'),
        ),
    ]
